import { renderNotesSection } from '../official-notes/render'
import { GENERATOR_SCRIPT } from '../wrpocket/render'
import type { EntryRef, FieldChange, Flag, PatchDiff, ReportedDiff } from './types'

const SEVERITY_LABEL: Record<Flag['severity'], string> = {
  removed: 'removed from wrpocket',
  changed: 'changed',
  notes: 'in the official notes, wrpocket unchanged',
}

const label = (ref: EntryRef): string => `${ref.kind} ${ref.id} (${ref.name})`

function renderChange(change: FieldChange): string[] {
  if (change.wordDiff === undefined) return [`- \`${change.field}\`: ${change.before} → ${change.after}`]
  const numbers = change.numbers ?? []
  const summary = numbers.length === 0
    ? 'wording only'
    : `numbers ${numbers.map(({ before, after }) => `${before || '∅'} → ${after || '∅'}`).join(', ')}`
  return [
    `- \`${change.field}\`: ${summary}`,
    '',
    `  <details><summary>text diff</summary>\n\n${change.wordDiff}\n\n</details>`,
    '',
  ]
}

function renderEntry(
  heading: string, goldens: string[], changes: FieldChange[], inNotes: boolean | null = null, notesLines: string[] = [],
): string[] {
  return [
    `### ${heading}`, '',
    `Goldens: ${goldens.length === 0 ? 'none' : goldens.join(', ')}`, '',
    ...(inNotes === null ? [] : [`In the official notes: ${inNotes ? 'yes' : 'no'}`, '']),
    ...changes.flatMap(renderChange),
    ...notesLines,
    '',
  ]
}

/** Whether the official notes mention the flagged entry; null when there is no found notes page to ask. */
function mentionedInNotes(diff: PatchDiff, flag: Flag): boolean | null {
  const notes = diff.officialNotes
  if (notes === null || !notes.found) return null
  return notes.mentioned.some((entry) => entry.ref.kind === flag.kind && entry.ref.id === flag.id)
}

/** The notes lines behind a notes-only flag, which has no wrpocket changes of its own to show. */
function notesLinesFor(diff: PatchDiff, flag: Flag): string[] {
  if (flag.severity !== 'notes' || diff.officialNotes === null) return []
  return diff.officialNotes.mentioned
    .filter((entry) => entry.ref.kind === flag.kind && entry.ref.id === flag.id)
    .flatMap((entry) => entry.lines.map((line) => `- ${line.group === null ? '' : `${line.group}: `}${line.text} (${line.status})`))
}

const orNone = (lines: string[]): string[] => (lines.length === 0 ? ['None.', ''] : lines)

const renderDiffs = (entries: ReportedDiff[]): string[] =>
  orNone(entries.flatMap((entry) => renderEntry(label(entry), entry.goldens, entry.changes)))

/** Renders PATCH_DIFF.md: summary, needs review, auto-applied items, notes cross-check, carried staleness, changes, added, removed, mapper notes. */
export function renderPatchDiff(diff: PatchDiff): string {
  const lines = [
    `# Patch diff: ${diff.from} → ${diff.to}`, '',
    `Generated by \`${GENERATOR_SCRIPT}\` from the wrpocket snapshots (${diff.from} updated ${diff.fromUpdated}, `
      + `${diff.to} updated ${diff.toUpdated}). Every value is unverified until checked in-game.`, '',
    `- ${diff.needsReview.length} hand-modelled entries need review`,
    `- ${diff.autoApplied.length} hand-modelled items took number-only changes automatically (confirmed by the official notes)`,
    `- ${diff.items.length} items and ${diff.champions.length} champions changed, ${diff.added.length} added, ${diff.removed.length} removed`,
    '- Changes to generated entries are already applied; they are listed for information.', '',
    '## Needs review', '',
    'Clear a flag by writing an override in `overrides.ts` (values changed) or adding the id to '
      + '`reviewed.ts` with a note (nothing we model changed).', '',
    ...orNone(diff.needsReview.flatMap((flag) => renderEntry(
      `${label(flag)}: ${SEVERITY_LABEL[flag.severity]}`, flag.goldens, flag.changes, mentionedInNotes(diff, flag), notesLinesFor(diff, flag),
    ))),
    '## Applied automatically', '',
    'Hand-modelled items whose only changes are in the name, price, tier, recipe or stat values, or numbers in the '
      + 'description that `src/patches/text-links.ts` ties to the model, and which the official notes mention with every '
      + 'new number matching wrpocket. The overlay applies these (`src/patches/source-sync.ts`, `generated/text-sync.ts`), '
      + 'so no override is needed. Changes the notes don\'t confirm stay under Needs review; list a field in the item\'s '
      + '`sourcePins` to keep a hand-written value instead.', '',
    ...renderDiffs(diff.autoApplied),
    ...(diff.textSync.length === 0 ? [] : [
      'Effect numbers taken from the text:', '',
      ...diff.textSync.map((update) => `- ${update.itemId} \`${update.effectId === undefined ? '' : `${update.effectId}.`}${update.path}\` = ${update.value} (text ${update.note})`),
      '',
    ]),
    ...renderNotesSection(diff.officialNotes),
    '## Still stale from earlier patches', '',
    ...orNone(diff.carriedStale.map((entry) => `- ${label(entry)}, stale since ${entry.since}`)),
    ...(diff.carriedStale.length > 0 ? [''] : []),
    '## Changed champions', '', ...renderDiffs(diff.champions),
    '## Changed items', '', ...renderDiffs(diff.items),
    '## Added', '', ...orNone(diff.added.map((entry) => `- ${label(entry)}`)),
    ...(diff.added.length > 0 ? [''] : []),
    '## Removed', '', ...orNone(diff.removed.map((entry) => `- ${label(entry)}`)),
    ...(diff.removed.length > 0 ? [''] : []),
    '## Mapper notes', '',
    '### New', '', ...orNone(diff.mapperNotes.added.map((note) => `- ${note.subject}: ${note.note}`)),
    ...(diff.mapperNotes.added.length > 0 ? [''] : []),
    '### Gone', '', ...orNone(diff.mapperNotes.removed.map((note) => `- ${note.subject}: ${note.note}`)),
  ]
  return `${lines.join('\n').replace(/\n{3,}/g, '\n\n').trimEnd()}\n`
}
