import { GENERATOR_SCRIPT } from '../wrpocket/render'
import type { EntryRef, FieldChange, PatchDiff, ReportedDiff } from './types'

const label = (ref: EntryRef): string => `${ref.kind} ${ref.id} (${ref.name})`

function renderChange(change: FieldChange): string[] {
  if (change.wordDiff === undefined) return [`- \`${change.field}\`: ${change.before} → ${change.after}`]
  const numbers = change.numbers ?? []
  const summary = numbers.length === 0
    ? 'wording only'
    : `numbers ${numbers.map(({ before, after }) => `${before || '∅'} → ${after || '∅'}`).join(', ')}`
  return [
    `- \`${change.field}\`: ${summary}`,
    '',
    `  <details><summary>text diff</summary>\n\n${change.wordDiff}\n\n</details>`,
    '',
  ]
}

function renderEntry(heading: string, goldens: string[], changes: FieldChange[]): string[] {
  return [
    `### ${heading}`, '',
    `Goldens: ${goldens.length === 0 ? 'none' : goldens.join(', ')}`, '',
    ...changes.flatMap(renderChange),
    '',
  ]
}

const orNone = (lines: string[]): string[] => (lines.length === 0 ? ['None.', ''] : lines)

const renderDiffs = (entries: ReportedDiff[]): string[] =>
  orNone(entries.flatMap((entry) => renderEntry(label(entry), entry.goldens, entry.changes)))

/** Renders PATCH_DIFF.md: summary, needs review, carried staleness, changes, added, removed, mapper notes. */
export function renderPatchDiff(diff: PatchDiff): string {
  const lines = [
    `# Patch diff: ${diff.from} → ${diff.to}`, '',
    `Generated by \`${GENERATOR_SCRIPT}\` from the wrpocket snapshots (${diff.from} updated ${diff.fromUpdated}, `
      + `${diff.to} updated ${diff.toUpdated}). Every value is unverified until checked in-game.`, '',
    `- ${diff.needsReview.length} hand-modelled entries need review`,
    `- ${diff.items.length} items and ${diff.champions.length} champions changed, ${diff.added.length} added, ${diff.removed.length} removed`,
    '- Changes to generated entries are already applied; they are listed for information.', '',
    '## Needs review', '',
    'Clear a flag by writing an override in `overrides.ts` (values changed) or adding the id to '
      + '`reviewed.ts` with a note (nothing we model changed).', '',
    ...orNone(diff.needsReview.flatMap((flag) => renderEntry(
      `${label(flag)}: ${flag.severity === 'removed' ? 'removed from wrpocket' : 'changed'}`, flag.goldens, flag.changes,
    ))),
    '## Still stale from earlier patches', '',
    ...orNone(diff.carriedStale.map((entry) => `- ${label(entry)}, stale since ${entry.since}`)),
    ...(diff.carriedStale.length > 0 ? [''] : []),
    '## Changed champions', '', ...renderDiffs(diff.champions),
    '## Changed items', '', ...renderDiffs(diff.items),
    '## Added', '', ...orNone(diff.added.map((entry) => `- ${label(entry)}`)),
    ...(diff.added.length > 0 ? [''] : []),
    '## Removed', '', ...orNone(diff.removed.map((entry) => `- ${label(entry)}`)),
    ...(diff.removed.length > 0 ? [''] : []),
    '## Mapper notes', '',
    '### New', '', ...orNone(diff.mapperNotes.added.map((note) => `- ${note.subject}: ${note.note}`)),
    ...(diff.mapperNotes.added.length > 0 ? [''] : []),
    '### Gone', '', ...orNone(diff.mapperNotes.removed.map((note) => `- ${note.subject}: ${note.note}`)),
  ]
  return `${lines.join('\n').replace(/\n{3,}/g, '\n\n').trimEnd()}\n`
}
