import { basename } from 'node:path'
import type { SnapshotMeta } from './snapshot'

export type RunPlan =
  | { kind: 'bootstrap'; patch: string }
  | { kind: 'new-patch'; patch: string; previous: string }
  | { kind: 'refresh'; patch: string; previous: string | null }
  | { kind: 'up-to-date'; patch: string }

// The patch id becomes a folder name and an import path, so it must not be able to escape either.
function assertSafePatchId(patch: string): void {
  if (!/^[0-9A-Za-z.]+$/.test(patch) || /^\.+$/.test(patch)) {
    throw new Error(`invalid patch id '${patch}': expected letters, digits and dots only`)
  }
}

/** Decides what a run does given wrpocket's meta and the existing snapshots (oldest first). */
export function planRun(meta: SnapshotMeta, known: SnapshotMeta[], force: boolean): RunPlan {
  assertSafePatchId(meta.patch)
  const current = known[known.length - 1]
  if (current === undefined) return { kind: 'bootstrap', patch: meta.patch }
  if (meta.patch === current.patch) {
    if (meta.updated < current.updated) {
      throw new Error(`wrpocket's ${meta.patch} data (${meta.updated}) is older than the ${current.patch} snapshot (${current.updated})`)
    }
    if (meta.updated === current.updated && !force) return { kind: 'up-to-date', patch: meta.patch }
    return { kind: 'refresh', patch: meta.patch, previous: known[known.length - 2]?.patch ?? null }
  }
  if (known.some((entry) => entry.patch === meta.patch)) {
    throw new Error(`wrpocket is on ${meta.patch}, older than the current patch ${current.patch}`)
  }
  if (meta.updated <= current.updated) {
    throw new Error(`wrpocket's new patch ${meta.patch} (${meta.updated}) is not newer than ${current.patch} (${current.updated})`)
  }
  return { kind: 'new-patch', patch: meta.patch, previous: current.patch }
}

/** Reads patch and update time from a cache folder named <patch>-<YYYYMMDDhhmmss>. */
export function metaFromCacheDir(dir: string): SnapshotMeta {
  const match = /^(.+)-(\d{4})(\d{2})(\d{2})(\d{2})(\d{2})(\d{2})$/.exec(basename(dir))
  if (match === null) throw new Error(`cache folder '${basename(dir)}': expected <patch>-<YYYYMMDDhhmmss>`)
  const [, patch, year, month, day, hour, minute, second] = match
  return { patch, updated: `${year}-${month}-${day} ${hour}:${minute}:${second}` }
}

// Header lines that name the generator script; everything else must match for the determinism check.
const GENERATOR_LINE_RE = /^(\/\/ GENERATED by packages\/data\/scripts\/|\/\/ mapper and re-run `pnpm|Generated by `packages\/data\/scripts\/)/

/** Removes the generator-name header lines so files from the old and new script names compare equal. */
export function stripGeneratorHeader(text: string): string {
  return text.split('\n').filter((line) => !GENERATOR_LINE_RE.test(line)).join('\n')
}
