import { existsSync } from 'node:fs'
import { mkdir, writeFile } from 'node:fs/promises'
import { join } from 'node:path'
import type { ChangedIds, TextUpdate } from '../../src/patches/overlay'
import { GENERATOR_SCRIPT } from '../wrpocket/render'

/** Turns a patch id into a constant-safe suffix: '7.3a' -> '7_3A'. */
export function patchConst(id: string): string {
  return id.toUpperCase().replace(/[^A-Z0-9]/g, '_')
}

/** Names a patch's wrpocket provenance constant. */
export function provenanceName(id: string): string {
  return `WRPOCKET_${patchConst(id)}_PROVENANCE`
}

/** Renders src/patches/layers.ts for the given patch ids, oldest first. */
export function renderLayersModule(ids: string[]): string {
  return [
    `// GENERATED by ${GENERATOR_SCRIPT} from the snapshots in`,
    '// packages/data/snapshots/wrpocket, oldest first. Do not edit by hand.',
    "import type { PatchLayer } from './overlay'",
    ...ids.map((id) => `import { PATCH_LAYER as PATCH_${patchConst(id)} } from './${id}/layer'`),
    '',
    `export const PATCH_LAYERS: PatchLayer[] = [${ids.map((id) => `PATCH_${patchConst(id)}`).join(', ')}]`,
    '',
  ].join('\n')
}

/** Renders a patch's generated/changed-ids.ts. */
export function renderChangedIds(ids: ChangedIds, patch: string): string {
  return [
    `// GENERATED by ${GENERATOR_SCRIPT}: every wrpocket record that changed or disappeared in`,
    `// patch ${patch}, by this repo's id. The overlay marks inherited hand-modelled entries in it stale.`,
    "import type { ChangedIds } from '../../overlay'",
    '',
    `export const CHANGED_IDS: ChangedIds = ${JSON.stringify({ items: ids.items, champions: ids.champions }, null, 2)}`,
    '',
  ].join('\n')
}

/** Renders a patch's generated/text-sync.ts: effect numbers taken from wrpocket's text, confirmed by the official notes. */
export function renderTextSync(updates: TextUpdate[], patch: string): string {
  return [
    `// GENERATED by ${GENERATOR_SCRIPT}: hand-modelled effect numbers updated in patch ${patch} from`,
    "// wrpocket's description text, each confirmed by the official notes (see src/patches/text-links.ts).",
    "import type { TextUpdate } from '../../overlay'",
    '',
    `export const TEXT_SYNC: TextUpdate[] = ${JSON.stringify(updates, null, 2)}`,
    '',
  ].join('\n')
}

/** The stub files a new patch folder starts with, by file name. */
export function scaffoldFiles(patch: string): Record<string, string> {
  return {
    'provenance.ts': [
      "import type { Provenance } from '@wr-calc/schema'",
      '',
      `/** Every value imported from wrpocket.app for patch ${patch}; unverified until checked in-game. */`,
      `export const ${provenanceName(patch)}: Provenance = {`,
      `  source: 'wiki', patch: '${patch}', verifiedInGame: false,`,
      '}',
      '',
    ].join('\n'),
    'overrides.ts': [
      "import type { Champion, Item } from '@wr-calc/schema'",
      '',
      `// Hand-modelled entries re-written for patch ${patch}. Each replaces the inherited entry with the`,
      '// same id and clears its stale flag.',
      'export const OVERRIDE_ITEMS: Item[] = []',
      'export const OVERRIDE_CHAMPIONS: Champion[] = []',
      '',
    ].join('\n'),
    'reviewed.ts': [
      "import type { ReviewedEntry } from '../overlay'",
      '',
      `// Flagged entries checked for patch ${patch} and found unaffected: their source changed, but`,
      '// nothing this repo models did. Each clears that entry\'s stale flag.',
      'export const REVIEWED: ReviewedEntry[] = []',
      '',
    ].join('\n'),
    'layer.ts': [
      "import type { PatchLayer } from '../overlay'",
      "import { CHANGED_IDS } from './generated/changed-ids'",
      "import { GENERATED_CHAMPIONS } from './generated/champions'",
      "import { GENERATED_ITEMS } from './generated/items'",
      "import { NOTES_FLAGGED, NOTES_REVIEWED } from './generated/notes-review'",
      "import { TEXT_SYNC } from './generated/text-sync'",
      "import { OVERRIDE_CHAMPIONS, OVERRIDE_ITEMS } from './overrides'",
      "import { REVIEWED } from './reviewed'",
      '',
      `/** Patch ${patch}: regenerated wrpocket data over the previous patch's hand-modelled entries. */`,
      'export const PATCH_LAYER: PatchLayer = {',
      `  id: '${patch}',`,
      '  generatedItems: GENERATED_ITEMS,',
      '  generatedChampions: GENERATED_CHAMPIONS,',
      '  overrideItems: OVERRIDE_ITEMS,',
      '  overrideChampions: OVERRIDE_CHAMPIONS,',
      '  reviewed: [...REVIEWED, ...NOTES_REVIEWED],',
      '  changedIds: {',
      '    items: [...CHANGED_IDS.items, ...NOTES_FLAGGED.items],',
      '    champions: [...CHANGED_IDS.champions, ...NOTES_FLAGGED.champions],',
      '  },',
      '  textSync: TEXT_SYNC,',
      '}',
      '',
    ].join('\n'),
  }
}

/** Writes each file that does not exist yet and returns the names it created; existing files are never touched. */
export async function writeMissingFiles(dir: string, files: Record<string, string>): Promise<string[]> {
  await mkdir(dir, { recursive: true })
  const created: string[] = []
  for (const [name, content] of Object.entries(files)) {
    const path = join(dir, name)
    if (existsSync(path)) continue
    await writeFile(path, content)
    created.push(name)
  }
  return created.sort()
}
