import { describe, it, expect } from 'vitest'
import { renderModule, renderReport } from '../../scripts/wrpocket/render'

const META = { patch: '7.3', updated: '2026-09-23 10:19:27' }
const PROVENANCE = { source: 'wiki' as const, patch: '7.3', verifiedInGame: false }

describe('renderModule', () => {
  const source = renderModule('GENERATED_ITEMS', 'Item', [
    { id: 'b-item', provenance: PROVENANCE },
    { id: 'a-item', provenance: PROVENANCE },
  ], META)

  it('writes the generated-file header with source and patch', () => {
    expect(source).toContain('// GENERATED by packages/data/scripts/import-wrpocket.ts')
    expect(source).toContain('patch 7.3, updated 2026-09-23 10:19:27')
    expect(source).toContain("import type { Item } from '@wr-calc/schema'")
    expect(source).toContain("import { WRPOCKET_7_3_PROVENANCE } from '../provenance'")
    expect(source).toContain('export const GENERATED_ITEMS: Item[] = [')
  })

  it('references the provenance constant instead of inlining it', () => {
    expect(source).toContain('"provenance": WRPOCKET_7_3_PROVENANCE')
    expect(source).not.toContain('"source": "wiki"')
    expect(source).not.toContain('__WRPOCKET_PROVENANCE__')
  })

  it('sorts entries by id', () => {
    expect(source.indexOf('"a-item"')).toBeLessThan(source.indexOf('"b-item"'))
  })
})

describe('renderReport', () => {
  it('lists the summary and only subjects that have notes', () => {
    const report = renderReport(META, [
      { subject: 'item foo', notes: ['note one', 'note two'] },
      { subject: 'item clean', notes: [] },
    ], ['171 items'])
    expect(report).toContain('# wrpocket import report (patch 7.3, updated 2026-09-23 10:19:27)')
    expect(report).toContain('- 171 items')
    expect(report).toContain('## item foo\n\n- note one\n- note two')
    expect(report).not.toContain('item clean')
  })
})
