// Fetches each champion's CN Diamond+ builds from wrchina.gg and writes src/cn-builds/generated/latest.ts.
// Usage: pnpm --filter @wr-calc/data cn-builds:update
import { mkdir, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { z } from 'zod'
import { normalizeId } from '../src/wrpocket-ids'
import { BUILD_URL, RawBuildSchema, mapCnBuilds } from './cn-builds/map'
import type { RawBuild } from './cn-builds/map'
import { HERO_LIST_URL, RawHeroListSchema, championIdFromPoster } from './cn-stats/map'

const OUT_FILE = join(dirname(fileURLToPath(import.meta.url)), '..', 'src', 'cn-builds', 'generated', 'latest.ts')
const WRPOCKET = 'https://wrpocket.app/site_data'

async function fetchJson(url: string): Promise<unknown> {
  let lastError: unknown
  for (let attempt = 1; attempt <= 4; attempt++) {
    try {
      const response = await fetch(url)
      if (response.status === 404) return null
      if (!response.ok) throw new Error(`GET ${url} failed: HTTP ${response.status}`)
      return JSON.parse(await response.text())
    } catch (error) {
      lastError = error
      await new Promise((resolve) => setTimeout(resolve, 2 ** attempt * 1000))
    }
  }
  throw lastError
}

// wrpocket's raw site_data carries Tencent's ids as source_id; our snapshots drop it for items.
const SourceIdsSchema = z.array(z.object({ id: z.string(), source_id: z.union([z.string(), z.number()]) }).passthrough())
async function sourceIdMap(file: string): Promise<Map<string, string>> {
  const rows = SourceIdsSchema.parse(await fetchJson(`${WRPOCKET}/${file}`))
  return new Map(rows.map((row) => [String(row.source_id), normalizeId(row.id)]))
}

const { CURRENT_PATCH, getPatchDataset } = await import('../src/patches/registry')
const known = new Set(getPatchDataset(CURRENT_PATCH).champions.map((champion) => champion.id))
const heroList = RawHeroListSchema.parse(await fetchJson(HERO_LIST_URL))
const championIdByHero = new Map(Object.values(heroList.heroList)
  .map((hero) => [hero.heroId, championIdFromPoster(hero.poster)] as const)
  .filter(([, id]) => known.has(id)))

const raws: RawBuild[] = []
for (const heroId of Object.keys(heroList.heroList).sort()) {
  const body = await fetchJson(BUILD_URL(heroId))
  if (body !== null) raws.push(RawBuildSchema.parse(body))
  await new Promise((resolve) => setTimeout(resolve, 250)) // ponytail: fixed politeness delay, ~1 min for all heroes
}
const snapshot = mapCnBuilds(raws, championIdByHero, await sourceIdMap('items.json'), await sourceIdMap('runes.json'), new Date().toISOString())
await mkdir(dirname(OUT_FILE), { recursive: true })
await writeFile(OUT_FILE, [
  '// GENERATED by packages/data/scripts/cn-builds-update.ts. Do not edit by hand.',
  `// Source: ${snapshot.source} (CN server, Diamond+, stats for ${snapshot.statDate}).`,
  "import type { CnBuildsSnapshot } from '../types'",
  '',
  `export const CN_BUILDS: CnBuildsSnapshot = ${JSON.stringify(snapshot)}`,
  '',
].join('\n'))
console.log(`CN builds for ${snapshot.statDate}: ${Object.keys(snapshot.champions).length} champions from ${raws.length} files; unmapped ${JSON.stringify(snapshot.unmapped)}.`)
