// Snapshots Tencent's CN item and hero feed, logs what changed since the last snapshot, and writes
// src/cn-preview/generated/latest.ts. Usage: pnpm --filter @wr-calc/data cn-preview:update
import { existsSync } from 'node:fs'
import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import type { CnPreview } from '../src/cn-preview/types'
import { normalizeId } from '../src/wrpocket-ids'
import { fetchJson, sourceIdMap } from './cn-fetch'
import { ITEM_STATS, RawEquipSchema, RawHeroSchema, diffFlat, differsNow, flatten } from './cn-preview/flatten'
import type { Flat, LiveLookup, RawHero } from './cn-preview/flatten'
import { HERO_LIST_URL, RawHeroListSchema, championIdFromPoster } from './cn-stats/map'
import { readSnapshot } from './patch/snapshot-io'
import { stableStringify } from './patch/stable-json'

const DATA_ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')
const FEED = 'https://game.gtimg.cn/images/lgamem/act/lrlib/js'
const SNAPSHOT_FILE = join(DATA_ROOT, 'snapshots', 'tencent', 'latest.json')
const OUT_FILE = join(DATA_ROOT, 'src', 'cn-preview', 'generated', 'latest.ts')
// wrpocket's ability keys, in Tencent's spell order.
const WRPOCKET_SLOTS: Record<string, string> = { p: 'パッシブ', q: 'スキル1', w: 'スキル2', e: 'スキル3', r: 'アルティメット' }

interface TencentSnapshot { version: string; fileTime: string; entries: Flat }

const { CURRENT_PATCH } = await import('../src/patches/registry')
const live = await readSnapshot(join(DATA_ROOT, 'snapshots', 'wrpocket', CURRENT_PATCH))
const liveItems = new Map(live.items.map((item) => [normalizeId(item.id), item]))
const liveChampions = new Map(live.champions.map((champion) => [normalizeId(champion.id), champion]))
const lookup: LiveLookup = (entry, field) => {
  const [kind, id] = entry.split(':')
  if (kind === 'item') {
    const item = liveItems.get(id)
    if (item === undefined) return null
    if (field === 'price') return item.price
    if (field === 'from') return item.components.map(normalizeId).sort().join(',')
    const stat = ITEM_STATS[field.replace(/^stat\./, '')]
    return field.startsWith('stat.') && stat !== undefined ? String(item.numeric_stats[stat[0]] ?? 0) : null
  }
  const [slot, type] = field.split('.')
  const ability = liveChampions.get(id)?.abilities[WRPOCKET_SLOTS[slot] ?? '']
  // Tencent truncates cooldowns (9.5 -> 9), so cd rows can't be compared.
  if (ability === undefined || type === 'cd') return null
  return ability.scaling.find((row) => row.type === type)?.value ?? null
}

const heroList = RawHeroListSchema.parse(await fetchJson(`${HERO_LIST_URL}`))
const championIds = new Map(Object.values(heroList.heroList).map((hero) => [hero.heroId, championIdFromPoster(hero.poster)]))
const equip = RawEquipSchema.parse(await fetchJson(`${FEED}/equip/equip.js`))
const heroes: RawHero[] = []
for (const heroId of Object.keys(heroList.heroList).sort()) {
  const body = await fetchJson(`${FEED}/hero/${heroId}.js`)
  if (body !== null) heroes.push(RawHeroSchema.parse(body))
}
const current: TencentSnapshot = {
  version: equip.version,
  fileTime: [equip.fileTime, ...heroes.map((hero) => hero.fileTime)].sort().at(-1)!,
  entries: flatten(equip, heroes, await sourceIdMap('items.json'), championIds),
}

const previous: TencentSnapshot | null = existsSync(SNAPSHOT_FILE) ? JSON.parse(await readFile(SNAPSHOT_FILE, 'utf-8')) : null
const { CN_PREVIEW } = await import('../src/cn-preview/generated/latest')
const changes = previous === null ? [] : diffFlat(previous.entries, current.entries, lookup)
const preview: CnPreview = {
  checkedAt: new Date().toISOString(), version: current.version, fileTime: current.fileTime,
  log: changes.length === 0 ? CN_PREVIEW.log : [{ fileTime: current.fileTime, version: current.version, changes }, ...CN_PREVIEW.log],
  differsNow: differsNow(current.entries, lookup),
}
await mkdir(dirname(SNAPSHOT_FILE), { recursive: true })
await writeFile(SNAPSHOT_FILE, stableStringify(current))
await writeFile(OUT_FILE, [
  '// GENERATED by packages/data/scripts/cn-preview-update.ts. Do not edit by hand.',
  `// Source: ${FEED} (CN ${preview.version}, files up to ${preview.fileTime}).`,
  "import type { CnPreview } from '../types'",
  '',
  `export const CN_PREVIEW: CnPreview = ${JSON.stringify(preview, null, 1)}`,
  '',
].join('\n'))
console.log(`CN ${current.version} (${current.fileTime}): ${Object.keys(current.entries).length} entries, `
  + `${changes.length} changes since the last snapshot, ${preview.differsNow.length} fields differ from live ${CURRENT_PATCH}.`)
