// Fetches the CN server's win/pick/ban rates and writes src/cn-stats/generated/latest.ts.
// Usage: pnpm --filter @wr-calc/data cn-stats:update
import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { HERO_LIST_URL, RANK_LIST_URL, RawHeroListSchema, RawRankListSchema, mapCnStats } from './cn-stats/map'

const DATA_ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')
const OUT_FILE = join(DATA_ROOT, 'src', 'cn-stats', 'generated', 'latest.ts')
const CHAMPIONS_SNAPSHOT_ROOT = join(DATA_ROOT, 'snapshots', 'wrpocket')

/** Tencent's CDN sometimes resets connections, so each fetch gets a few tries. */
async function fetchJson(url: string): Promise<unknown> {
  let lastError: unknown
  for (let attempt = 1; attempt <= 4; attempt++) {
    try {
      const response = await fetch(url)
      if (!response.ok) throw new Error(`GET ${url} failed: HTTP ${response.status}`)
      return JSON.parse(await response.text())
    } catch (error) {
      lastError = error
      await new Promise((resolve) => setTimeout(resolve, 2 ** attempt * 1000))
    }
  }
  throw lastError
}

async function knownChampionIds(): Promise<Set<string>> {
  const { CURRENT_PATCH } = await import('../src/patches/registry')
  const raw = JSON.parse(await readFile(join(CHAMPIONS_SNAPSHOT_ROOT, CURRENT_PATCH, 'champions.json'), 'utf-8')) as Array<{ id: string }>
  return new Set(raw.map((champion) => champion.id))
}

const rankList = RawRankListSchema.parse(await fetchJson(RANK_LIST_URL))
if (rankList.result !== 0) throw new Error(`${RANK_LIST_URL} returned result ${rankList.result}`)
const heroList = RawHeroListSchema.parse(await fetchJson(HERO_LIST_URL))
const snapshot = mapCnStats(rankList, heroList, await knownChampionIds(), new Date().toISOString())
await mkdir(dirname(OUT_FILE), { recursive: true })
await writeFile(OUT_FILE, [
  '// GENERATED by packages/data/scripts/cn-stats-update.ts. Do not edit by hand.',
  `// Source: ${RANK_LIST_URL} (CN server, stats for ${snapshot.statDate}).`,
  "import type { CnStatsSnapshot } from '../types'",
  '',
  `export const CN_STATS: CnStatsSnapshot = ${JSON.stringify(snapshot, null, 1)}`,
  '',
].join('\n'))
const rows = Object.values(snapshot.ranks).flatMap((lanes) => Object.values(lanes)).reduce((sum, list) => sum + list.length, 0)
console.log(`CN stats for ${snapshot.statDate} (CN ${snapshot.cnVersion}): ${rows} rows, ${snapshot.unmapped.length} unmapped hero ids.`)
