// Prints a practice-tool test sheet: for each modelled item, rune and spell that deals damage, a one-item setup, the
// combo to play, and the numbers the engine predicts the practice tool will show (after armor/MR).
// Usage: pnpm --filter @wr-calc/data test-sheet > ../../docs/test-sheets/predictions-7.3a.md
import type { Build, Effect } from '@wr-calc/schema'
import { combatantFromChampion, combatantFromDummy, simulateCombo } from '@wr-calc/calc'
import type { ComboAction } from '@wr-calc/calc'
import { CURRENT_PATCH, getPatchDataset } from '../src/patches/registry'

const dataset = getPatchDataset(CURRENT_PATCH)
const TARGET = { hp: 10000, armor: 100, mr: 100 }
// Ambessa for physical items, Annie for magic ones: the champions the golden cases already use.
const PHYSICAL = 'ambessa'
const MAGIC = 'annie'

interface Row {
  kind: 'Item' | 'Rune' | 'Spell'
  name: string
  champion: string
  build: Build
  combo: ComboAction[]
  effectIds: string[]
  /** Fraction of max HP the dummy starts at (below-half-Health effects need it low). */
  startHp: number
}

// Every boolean input the effects declare, switched on: the tester sets up the condition the toggle stands for.
// Except "starts on cooldown" toggles, which would hide the proc.
const togglesOn = (effects: Effect[]): Build['inputs'] => {
  const cooldownInputs = new Set(effects.flatMap((effect) =>
    effect.kind === 'abilityHitProc' && effect.startOnCooldownInputId !== undefined ? [effect.startOnCooldownInputId] : []))
  return Object.fromEntries(effects.flatMap((effect) => (effect.inputs ?? [])
    .filter((input) => input.type === 'boolean' && !cooldownInputs.has(input.id)).map((input) => [input.id, true])))
}
const startHpFor = (effects: Effect[]): number => {
  if (effects.some((effect) => effect.kind === 'execute')) return 0.08
  return effects.some((effect) => effect.condition?.type === 'targetHpBelow') ? 0.45 : 1
}

const damaging = (effects: Effect[]) => effects.filter((effect) => [
  'onHit', 'spellblade', 'procEveryN', 'dot', 'active', 'abilityHitProc', 'damageWindowProc', 'hitStackProc',
  'combatAura', 'execute', 'custom',
].includes(effect.kind)).map((effect) => effect.id)

// One combo for everything but actives and auras: abilities (R included, for ultimate triggers) and 7 attacks.
const STANDARD: ComboAction[] = ['Q', 'AA', 'W', 'AA', 'R', 'AA', 'AA', 'AA', 'AA', 'AA', 'wait:3']

function comboFor(effects: Effect[], activeAction?: ComboAction): ComboAction[] {
  if (activeAction) return [activeAction, 'wait:5']
  if (effects.some((effect) => effect.kind === 'combatAura')) return ['AA', 'wait:4.5']
  return STANDARD
}

const rows: Row[] = []
for (const item of dataset.items) {
  const ids = damaging(item.effects)
  if (ids.length === 0) continue
  // wrpocket's category, kept as the first tag: 'magic' items go on Annie, the rest on Ambessa.
  const magic = item.tags[0] === 'magic'
  const active = item.effects.some((effect) => effect.kind === 'active') ? `item:${item.id}` as ComboAction : undefined
  const inputs = togglesOn(item.effects)
  rows.push({
    kind: 'Item', name: item.name, champion: magic ? MAGIC : PHYSICAL,
    build: item.tier === 'boots' ? { items: [], boots: item.id, runes: [], inputs } : { items: [item.id], runes: [], inputs },
    combo: comboFor(item.effects, active), effectIds: ids, startHp: startHpFor(item.effects),
  })
}
for (const rune of dataset.runes) {
  const ids = damaging(rune.effects)
  if (ids.length === 0) continue
  rows.push({
    kind: 'Rune', name: rune.name, champion: PHYSICAL, build: { items: [], runes: [rune.id], inputs: togglesOn(rune.effects) },
    combo: comboFor(rune.effects), effectIds: ids, startHp: startHpFor(rune.effects),
  })
}
for (const spell of dataset.spells) {
  const ids = damaging(spell.effects)
  if (ids.length === 0) continue
  rows.push({
    kind: 'Spell', name: spell.name, champion: PHYSICAL, build: { items: [], runes: [], spells: [spell.id], inputs: togglesOn(spell.effects) },
    combo: [`spell:${spell.id}`, 'wait:5'], effectIds: ids, startHp: 1,
  })
}

// Practice-tool numbers are whole; show a decimal only where rounding would hide the value.
const show = (value: number): string => (value >= 10 ? String(Math.round(value)) : String(Math.round(value * 10) / 10))
const championName = (id: string) => dataset.champions.find((champion) => champion.id === id)?.name ?? id
const lines = [
  `# Predicted practice-tool numbers (patch ${CURRENT_PATCH})`, '',
  'Generated by `packages/data/scripts/test-sheet.ts`. Each row is one champion at level 15 with only that item, rune or',
  `spell (max ability ranks, no other runes), against a ${TARGET.hp} HP / ${TARGET.armor} armor / ${TARGET.mr} MR dummy,`,
  'with crits off. Play the combo and compare the numbers the item, rune or spell shows. Toggles the effect declares',
  '(e.g. "target crowd-controlled") are on, so set that condition up in game. Effects that need the target below half',
  'Health start the dummy at 45% (8% for The Collector). Attacks are taken to land instantly in sequence at your',
  'attack speed. A mismatch goes on `pending-checks.md`.', '',
  '| | Setup | Dummy HP | Combo | Predicted numbers |', '|---|---|---:|---|---|',
]
for (const row of rows) {
  let predicted: string
  try {
    const attacker = combatantFromChampion(dataset.champions.find((champion) => champion.id === row.champion)!, 15, row.build, dataset.catalog)
    const result = simulateCombo(attacker, combatantFromDummy({ kind: 'dummy', ...TARGET, startHpFraction: row.startHp }), row.combo, { critMode: 'never' })
    const values = result.instances.flatMap((instance) => {
      if (row.effectIds.includes(instance.source.id)) return [`${show(instance.mitigated)} ${instance.type}`]
      const part = instance.parts?.find((entry) => row.effectIds.includes(entry.source.id))
      // A merged physical part shows inside the attack's own number, so give the attack's total.
      return part ? [`${Math.round(instance.mitigated)} (attack incl. ${Math.round(part.amount)} raw)`] : []
    })
    predicted = values.length === 0 ? 'nothing (needs a toggle or a longer combo)' : values.join(', ')
  } catch (error) {
    predicted = `error: ${error instanceof Error ? error.message : String(error)}`
  }
  lines.push(`| ${row.kind} | ${championName(row.champion)} + ${row.name} | ${Math.round(row.startHp * 100)}% | ${row.combo.join(' ')} | ${predicted} |`)
}
console.log(lines.join('\n'))
