import { GENERATOR_SCRIPT } from '../wrpocket/render'
import type { NotesCrossCheck } from './types'

const plural = (count: number, one: string, many: string): string => `${count} ${count === 1 ? one : many}`

/** Renders the PATCH_DIFF.md "Official notes cross-check" section; [] when no notes stage ran. */
export function renderNotesSection(check: NotesCrossCheck | null): string[] {
  if (check === null) return []
  const heading = ['## Official notes cross-check', '']
  if (!check.found) return [...heading, `Official notes not found at ${check.url}; nothing auto-cleared (use --notes-url).`, '']
  return [
    ...heading,
    `From the [official notes](${check.url}), published ${(check.published ?? '').slice(0, 10)}.`, '',
    `- ${plural(check.autoReviewed.length, 'flag', 'flags')} auto-cleared as wrpocket-only`,
    `- ${plural(check.notesFlags.length, 'hand-modelled entry', 'hand-modelled entries')} changed in the notes but not in wrpocket`,
    `- ${check.mentioned.length} notes entries matched, ${check.unmatched.length} unmatched, ${check.excludedCount} game-mode / system entries skipped`, '',
    '"Reflected" means every number in a line\'s new value appears somewhere in wrpocket\'s record for that '
      + 'entry. It is a heuristic for spotting wrpocket lagging behind the notes; it never clears a flag.', '',
    '### Auto-cleared', '',
    ...(check.autoReviewed.length === 0 ? ['None.'] : check.autoReviewed.map((entry) => `- ${entry.kind} ${entry.id}: ${entry.note}`)), '',
    '### Matched notes entries', '',
    ...(check.mentioned.length === 0 ? ['None.'] : check.mentioned.flatMap((entry) => [
      `- ${entry.ref.kind} ${entry.ref.id} (${entry.ref.name}): ${entry.status}`,
      ...entry.lines.map((line) => `  - ${line.group === null ? '' : `${line.group}: `}${line.text} (${line.status})`),
    ])), '',
    '### Unmatched notes entries', '',
    ...(check.unmatched.length === 0 ? ['None.'] : check.unmatched.map((entry) => `- ${entry.section || '(champion card)'}: ${entry.heading}`)), '',
  ]
}

/** Renders a patch's generated/notes-review.ts from the cross-check; empty lists without one. */
export function renderNotesReview(check: NotesCrossCheck | null, patch: string): string {
  const reviewed = check?.autoReviewed ?? []
  const flags = check?.notesFlags ?? []
  const flagged = {
    items: flags.filter((flag) => flag.kind === 'item').map((flag) => flag.id),
    champions: flags.filter((flag) => flag.kind === 'champion').map((flag) => flag.id),
  }
  const source = check === null || !check.found ? 'no official notes were found' : `the official notes at ${check.url}`
  return [
    `// GENERATED by ${GENERATOR_SCRIPT} from ${source}, for patch ${patch}.`,
    '// NOTES_REVIEWED clears flags the notes do not mention; NOTES_FLAGGED marks entries only the notes changed.',
    "import type { ChangedIds, ReviewedEntry } from '../../overlay'",
    '',
    `export const NOTES_REVIEWED: ReviewedEntry[] = ${JSON.stringify(reviewed, null, 2)}`,
    '',
    `export const NOTES_FLAGGED: ChangedIds = ${JSON.stringify(flagged, null, 2)}`,
    '',
  ].join('\n')
}
