import { describe, it, expect } from 'vitest'
import { metaFromCacheDir, planRun, stripGeneratorHeader } from '../../scripts/patch/run-plan'

const V73 = { patch: '7.3', updated: '2026-09-23 10:19:27' }
const V73A = { patch: '7.3a', updated: '2026-09-29 16:09:43' }

describe('planRun', () => {
  it('bootstraps when there is no snapshot yet', () => {
    expect(planRun(V73, [], false)).toEqual({ kind: 'bootstrap', patch: '7.3' })
  })

  it('starts a new patch over the current one', () => {
    expect(planRun(V73A, [V73], false)).toEqual({ kind: 'new-patch', patch: '7.3a', previous: '7.3' })
  })

  it('is up to date for the same patch and timestamp, unless forced', () => {
    expect(planRun(V73A, [V73, V73A], false)).toEqual({ kind: 'up-to-date', patch: '7.3a' })
    expect(planRun(V73A, [V73, V73A], true)).toEqual({ kind: 'refresh', patch: '7.3a', previous: '7.3' })
  })

  it('refreshes the current patch in place when wrpocket has newer data', () => {
    expect(planRun({ ...V73A, updated: '2026-10-02 00:00:00' }, [V73, V73A], false))
      .toEqual({ kind: 'refresh', patch: '7.3a', previous: '7.3' })
  })

  it('refuses an older patch id or an older timestamp', () => {
    expect(() => planRun(V73, [V73, V73A], false)).toThrow("wrpocket is on 7.3, older than the current patch 7.3a")
    expect(() => planRun({ ...V73A, updated: '2026-09-01 00:00:00' }, [V73, V73A], false)).toThrow(/older than the 7.3a snapshot/)
    expect(() => planRun({ patch: '7.4', updated: '2026-09-01 00:00:00' }, [V73, V73A], false)).toThrow(/not newer than/)
  })
})

describe('metaFromCacheDir', () => {
  it('reads the patch and timestamp from the cache folder name', () => {
    expect(metaFromCacheDir('/x/.cache/wrpocket/7.3-20260923101927')).toEqual(V73)
  })

  it('throws for a folder name without a timestamp', () => {
    expect(() => metaFromCacheDir('/x/7.3')).toThrow(/expected <patch>-<YYYYMMDDhhmmss>/)
  })
})

describe('stripGeneratorHeader', () => {
  it('drops only the lines naming the generator script', () => {
    const text = [
      '// GENERATED by packages/data/scripts/import-wrpocket.ts. Do not edit by hand: change the',
      '// mapper and re-run `pnpm --filter @wr-calc/data import:wrpocket` instead.',
      '// Source: https://wrpocket.app/site_data (patch 7.3, updated x).',
      'Generated by `packages/data/scripts/import-wrpocket.ts`. Every value is unverified until checked in-game.',
      'body',
    ].join('\n')
    expect(stripGeneratorHeader(text)).toBe('// Source: https://wrpocket.app/site_data (patch 7.3, updated x).\nbody')
  })
})
