import type { Provenance } from '@wr-calc/schema'
import type { RawMeta } from './raw-schemas'

const PROVENANCE_MARKER = '__WRPOCKET_PROVENANCE__'

/** Renders a generated TypeScript module exporting the given entries (sorted by id) as a typed array. */
export function renderModule(
  exportName: string, typeName: 'Item' | 'Champion',
  entries: Array<{ id: string; provenance: Provenance }>, meta: RawMeta,
): string {
  const sorted = [...entries].sort((a, b) => a.id.localeCompare(b.id))
  const body = JSON.stringify(sorted.map((entry) => ({ ...entry, provenance: PROVENANCE_MARKER })), null, 2)
    .replaceAll(`"${PROVENANCE_MARKER}"`, 'WRPOCKET_7_3_PROVENANCE')
  return [
    '// GENERATED by packages/data/scripts/import-wrpocket.ts. Do not edit by hand: change the',
    '// mapper and re-run `pnpm --filter @wr-calc/data import:wrpocket` instead.',
    `// Source: https://wrpocket.app/site_data (patch ${meta.patch}, updated ${meta.updated}).`,
    '// Reference values, not verified in-game. See IMPORT_REPORT.md for everything skipped or guessed.',
    `import type { ${typeName} } from '@wr-calc/schema'`,
    "import { WRPOCKET_7_3_PROVENANCE } from '../provenance'",
    '',
    `export const ${exportName}: ${typeName}[] = ${body}`,
    '',
  ].join('\n')
}

/** Renders the import report: a summary, then one section per subject that has notes. */
export function renderReport(
  meta: RawMeta, sections: Array<{ subject: string; notes: string[] }>, summary: string[],
): string {
  const lines = [
    `# wrpocket import report (patch ${meta.patch}, updated ${meta.updated})`,
    '',
    'Generated by `packages/data/scripts/import-wrpocket.ts`. Every value is unverified until checked in-game.',
    '',
    ...summary.map((line) => `- ${line}`),
  ]
  for (const { subject, notes } of sections) {
    if (notes.length === 0) continue
    lines.push('', `## ${subject}`, '', ...notes.map((note) => `- ${note}`))
  }
  return `${lines.join('\n')}\n`
}
