import type { Provenance } from '@wr-calc/schema'

export const GENERATOR_SCRIPT = 'packages/data/scripts/patch-update.ts'
const PROVENANCE_MARKER = '__WRPOCKET_PROVENANCE__'

/** Renders a generated TypeScript module exporting the given entries (sorted by id) as a typed array. */
export function renderModule(
  exportName: string, typeName: 'Item' | 'Champion',
  entries: Array<{ id: string; provenance: Provenance }>, meta: { patch: string; updated: string }, provenanceName: string,
): string {
  const sorted = [...entries].sort((a, b) => a.id.localeCompare(b.id))
  const body = JSON.stringify(sorted.map((entry) => ({ ...entry, provenance: PROVENANCE_MARKER })), null, 2)
    .replaceAll(`"${PROVENANCE_MARKER}"`, provenanceName)
  return [
    `// GENERATED by ${GENERATOR_SCRIPT}. Do not edit by hand: change the`,
    '// mapper and re-run `pnpm --filter @wr-calc/data patch:update` instead.',
    `// Source: https://wrpocket.app/site_data (patch ${meta.patch}, updated ${meta.updated}).`,
    '// Reference values, not verified in-game. See IMPORT_REPORT.md for everything skipped or guessed.',
    `import type { ${typeName} } from '@wr-calc/schema'`,
    `import { ${provenanceName} } from '../provenance'`,
    '',
    `export const ${exportName}: ${typeName}[] = ${body}`,
    '',
  ].join('\n')
}

/** Renders the import report: a summary, then one section per subject that has notes. */
export function renderReport(
  meta: { patch: string; updated: string }, sections: Array<{ subject: string; notes: string[] }>, summary: string[],
): string {
  const lines = [
    `# wrpocket import report (patch ${meta.patch}, updated ${meta.updated})`,
    '',
    `Generated by \`${GENERATOR_SCRIPT}\`. Every value is unverified until checked in-game.`,
    '',
    ...summary.map((line) => `- ${line}`),
  ]
  for (const { subject, notes } of sections) {
    if (notes.length === 0) continue
    lines.push('', `## ${subject}`, '', ...notes.map((note) => `- ${note}`))
  }
  return `${lines.join('\n')}\n`
}
